
services:
  app:
    build: .
    container_name: kbj
    ports:
      - "80:3000"
      - "8888:5432"
    environment:
      NODE_ENV: production
      DB_USER: kbjuser
      DB_PASS: kbjpass
      DB_NAME: kbj_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro
      - ./app:/app
volumes:
  db_data: